title: Mixed Signals
email: sethkranzler@gmail.com
description: >
  Mixed Signals is an emerging concert series highlighting new works in electronic and digital video, music and dance.
baseurl: ""
url: "http://mixedsignals.nyc"
twitter_username: polyrhythmic
github_username:  polyrhythmatic
logo: "/assets/images/logo.png"

collections:
  events:
    output: true
    permalink: /archive/:name
  events_description:
    output: true
    permalink: /:collection/:name

defaults:
 - scope:
     path: "_events"
   values:
     layout: page
 - scope:
     path: "_events_description"
   values:
     layout: description

kramdown:
  input: GFM

include:
  - _pages

sass:
  style: compressed

gems:
  - jekyll-sitemap

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "package.json"
  - "webpack.config.js"
  - "clearCache.js" 
  - "cloudflareKey.js"
