title: Mixed Signals
email: sethkranzler@gmail.com
description: >
  Mixed Signals is an emerging concert series highlighting new works in electronic and digital video, music and dance.
baseurl: ""
url: "https://mixedsignals.nyc"
twitter_username: polyrhythmic
github_username:  polyrhythmatic
logo: "/assets/images/logo.png"

collections:
  events:
    output: true
    permalink: /archive/:name
  event_photos:
    output: true
    permalink: /archive/photos_:name

defaults:
 - scope:
     path: "_events"
   values:
     layout: page
 - scope:
     path: "_event_photos"
   values:
     layout: event_photos

kramdown:
  input: GFM

include:
  - _pages

sass:
  style: compressed

gems:
  - jekyll-sitemap

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "package.json"
  - "webpack.config.js"
  - "clearCache.js" 
  - "cloudflareKey.js"
  - "screenshot.js"
  - "todo.md"
